
name: Deploy Laravel to Shared Hosting

on:
  push:
    branches: [ main ]  # O la rama que uses como principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to shared hosting via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navegar al directorio del proyecto
            cd /home/miagrone/invmaranionyfm.miagronegocio.com
            
            # Realizar pull desde GitHub
            git pull origin main
            
            # Instalar dependencias de Composer
            composer install --no-dev --optimize-autoloader
            
            # Instalar dependencias de NPM
            npm install
            
            # Compilar assets (Tailwind CSS)
            npm run build
            
            # Tareas de Laravel post-despliegue
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            
            # Corregir permisos si es necesario
            chmod -R 755 .
            chmod -R 777 storage
            chmod -R 777 bootstrap/cache