name:  Despliegue a subdominio via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configurar clave SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name:  Desplegar código al servidor por SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /home/miagrone/invmaranionfym.miagronegocio.com

            # Si ya está inicializado como repo, hacemos pull
            if [ -d .git ]; then
              git reset --hard
              git clean -fd
              git pull origin main
            else
              git clone https://github.com/kennymiller593/despliegue.git .
            fi

            composer install --no-dev --optimize-autoloader
            npm install
            npm run build
          EOF
