name: Deploy via SFTP

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 2: Instalar dependencias
      - name: Install dependencies
        run: |
          composer install --no-dev --optimize-autoloader
          npm install
          npm run build
          rm -rf node_modules  # No subir esta carpeta

      # Paso 3: Desplegar vía SFTP (¡Clave aquí!)
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          host: 'invmaranionfym.miagronegocio.com'
          port: '22'  # Puerto SFTP estándar
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          localPath: './'
          remotePath: '/home/miagrone/invmaranionfym.miagronegocio.com/'
          args: '-avz --delete'  # Habilita compresión y sincronización eficiente